GET http://localhost:3000/api/f1/createPredictionType HTTP/1.1
content-type: application/json

{
    "name": "Hungaru",
    "password": "devPassword",
    "weekendParts":[
        {"name":"FP1", "endTime":"2022-08-26T12:00:00.000Z"},
        {"name":"FP2", "endTime":"2022-08-26T13:00:00.000Z"},
        {"name":"FP3", "endTime":"2022-08-27T10:00:00.000Z"},
        {"name":"Qualifying", "endTime":"2022-08-27T14:00:00.000Z"},
        {"name":"Race", "endTime":"2022-08-28T13:00:00.000Z"}
    ]
}